---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bhim-volume
  labels:
    type: local
spec:
  storageClassName: ibmc-file-gold-gid
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
